services:
  ticket-io-backend:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: ticket-io-backend
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      - ticket-io-mysql

  ticket-io-mysql:
    image: mysql:latest
    container_name: ticket-io-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin!
      MYSQL_DATABASE: main
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  mysql_data:
